
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'bolt_dbt_googleads_package'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'bolt_dbt_googleads_package'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros","dbt_packages/bolt_dbt_utils/macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
    # General vars
    week_start: 'Monday' # Abbreviation and full name both work
    currency: "USD"

    # Googleads vars
    googleads_conversion_used_by_custom_conversions: 'all_conversions'   # Googleads custom conversions can use conversions or all_conversions

models:
  bolt_dbt_googleads_package:
    # Config indicated by + and applies to all files under models/example/
    base:
      +schema: googleads_base
      +materialized: table

    reporting:
      +schema: reporting
      +materialized: table
